[package]
name = "onlyswaps-verifier"
version.workspace = true
edition.workspace = true

[dependencies]
agent-utils.workspace = true
alloy = { workspace = true, features = ["default", "provider-ws"] }
anyhow.workspace = true
ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
async-stream = "0.3.6"
async-trait.workspace = true
axum = "0.8.4"
base64.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
config.workspace = true
dcipher-network = { workspace = true, features = ["libp2p", "transports", "replayable", "in_memory", "reader"] }
dcipher-signer = { workspace = true, features = ["rayon", "bn254", "sha3"] }
futures.workspace = true
generated.workspace = true
humantime-serde.workspace = true
libp2p.workspace = true
omnievent.workspace = true
serde.workspace = true
strum.workspace = true
superalloy.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tokio-stream.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json", "env-filter"] }
utils.workspace = true

[dev-dependencies]
speculoos = "0.13.0"
tempfile = "3.22.0"
