[agent]
healthcheck_listen_addr = "0.0.0.0"
healthcheck_port = 8081
log_level = "debug"
log_json = true

[[networks]]
chain_id = 43113
rpc_url = "wss://avalanche-fuji-c-chain-rpc.publicnode.com"
tokens = ["0x1b0F6cF6f3185872a581BD2B5a738EB52CCd4d76"]
router_address = "0x83b2dFc83E41a2398e28e31C352E1053805e4C16"

[[networks]]
chain_id = 84532
rpc_url = "wss://base-sepolia-rpc.publicnode.com"
tokens = ["0x1b0F6cF6f3185872a581BD2B5a738EB52CCd4d76"]
router_address = "0x83b2dFc83E41a2398e28e31C352E1053805e4C16"
