[package]
name = "onlyswaps-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
generated.workspace = true
superalloy.workspace = true
tracing.workspace = true
thiserror.workspace = true
