name: push-onlyswaps-state-api
on:
  push:
    branches:
      # all branches, docker image is only pushed on main
      - "*"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

env:
  SERVICE_ACCOUNT: github@randamu-prod.iam.gserviceaccount.com
  DOCKER_REGISTRY: europe-west1-docker.pkg.dev/randamu-prod/candyland
  IMAGE_MAINTAINER: "Randamu"
  IMAGE_VENDOR: "Randamu"

jobs:
  build-and-push:
    runs-on: "randamu-self-hosted-default"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/onlyswaps-state-api
          labels: |
            maintainer=${{ env.IMAGE_MAINTAINER }}
            org.opencontainers.image.title=onlyswaps-state-api
            org.opencontainers.image.description="a rust agent for storing state relating to onlyswaps"
            org.opencontainers.image.vendor=${{ env.IMAGE_VENDOR }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,value=main-latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=semver,pattern={{version}},event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # this might not work at all, but might work and 
          # allow us to bypass dockerhub ratelimit
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
          ## this does work to avoid the dockerhub ratelimit
          driver-opts: |
            image=mirror.gcr.io/moby/buildkit:buildx-stable-1
            network=host


      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/randa-mu/dcipher/onlyswaps-state-api:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ./bin/onlyswaps-state-api/Dockerfile
          cache-from: |
            type=registry,ref=${{ env.DOCKER_REGISTRY }}/onlyswaps-state-api-cache:${{ steps.meta.outputs.version }}
            type=registry,ref=${{ env.DOCKER_REGISTRY }}/onlyswaps-state-api-cache:main-latest
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/onlyswaps-state-api-cache:${{ steps.meta.outputs.version }},mode=max

      - name : extract binary
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run  : |
          docker pull ghcr.io/randa-mu/dcipher/onlyswaps-state-api:${{ steps.meta.outputs.version }}
          container=$(docker create ghcr.io/randa-mu/dcipher/onlyswaps-state-api:${{ steps.meta.outputs.version }})
          docker cp $container:usr/local/bin/onlyswaps-state-api /tmp/onlyswaps-state-api
          docker rm $container

      - name: upload binary to release
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes || true
          gh release upload ${{ github.ref_name }} /tmp/onlyswaps-state-api
