name: push-docker
on:
  push:
    branches:
      # all branches, docker image is only pushed on main
      - "*"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

env:
  SERVICE_ACCOUNT: github@randamu-prod.iam.gserviceaccount.com
  DOCKER_REGISTRY: europe-west1-docker.pkg.dev/randamu-prod/candyland
  IMAGE_MAINTAINER: "Randamu"
  IMAGE_VENDOR: "Randamu"

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        target:
          - image: 'blocklock-agent-rs'
            description: 'a rust agent for uploading signatures to blockchains'
            path: './blocklock-agent/Dockerfile'
          - image: 'dsigner'
            description: 'a distributed signing service'
            path: './dsigner/Dockerfile'
          - image: 'onlyswaps-verifier'
            description: 'a rust agent for verifying crosschain swaps'
            path: './onlyswaps-verifier/Dockerfile'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ matrix.target.image }}
          labels: |
            maintainer=${{ env.IMAGE_MAINTAINER }}
            org.opencontainers.image.title=${{ matrix.target.image }}
            org.opencontainers.image.description=${{ matrix.target.description }}
            org.opencontainers.image.vendor=${{ env.IMAGE_VENDOR }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=sha,prefix=
            type=ref,event=branch,suffix=-latest,enable=${{ startsWith(github.ref, 'refs/heads/') }}
            type=semver,pattern={{version}},event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # this might not work at all, but might work and
          # allow us to bypass dockerhub ratelimit for the buildkitd
          # step
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
          ## this does work to avoid the dockerhub ratelimit
          driver-opts: |
            image=mirror.gcr.io/moby/buildkit:buildx-stable-1
            network=host

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          # push on main and on tags
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ${{ matrix.target.path }}
          cache-from: |
            type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ matrix.target.image }}-cache:${{ steps.meta.outputs.version }}
            type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ matrix.target.image }}-cache:main-latest
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ matrix.target.image }}-cache:${{ steps.meta.outputs.version }},mode=max
